### ISSUE TITLE
Integration manager broken

### ISSUE THREAD

**Issue by stoically** [stoically/radical#29]
With the 1.6 RC it says: `Scalar-web No screen specified`

**Comment by auscompgeek** [comment]
I just tried with Dimension as well: `ERROR DOMException: "The operation is insecure."`

**Comment by stoically** [comment]
This and #28 doesn't happen for me in a new profile. Both errors come from code loaded from scalar-vector, which makes this hard to debug in the affected profile.

**Comment by auscompgeek** [comment]
Turns out this is caused by Firefox's tracking protection. Turning third-party cookie blocking to unvisited third-party is enough to break scalar. (I forgot I had tracking protection turned off on riot.im for the same reason.)

**Comment by stoically** [comment]
Can confirm, disabling Third-party cookies causes the problem. Thanks for investigating!

**Comment by stoically** [comment]
With Firefox 76 it's no longer possible to fix the bug by just disabling tracking protection for the WebExtension, it's required to globally allow third-party cookies. This is probably a Firefox bug since it still works on regular websites.

**Comment by auscompgeek** [comment]
FWIW, seems it's working again with Firefox 76.0.1.
